nextauthjs/next-auth-example:
  - source: apps/example-nextjs
    dest: .
    deleteOrphaned: true
  - .github/FUNDING.yml
  - LICENSE

nextauthjs/next-auth-gatsby-example:
  - source: apps/example-gatsby
    dest: .
    deleteOrphaned: true
  - .github/FUNDING.yml
  - LICENSE
