name: Types

on:
  push:
    branches:
      - main
      - beta
      - next
  pull_request:
    branches:
      - main
      - beta
      - next

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Check types
        run: npm run test:types
